on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

name: CI

jobs:

  php-tests:
    env:
      ENV_INTERACTIVE: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.0', '8.1' ]
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install dependencies
        run: composer install

      - name: Run unit tests
        run: vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.xml

      - name: Run other tests
        run: make full-test

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: false # optional (default = false)
          verbose: true # optional (default = false)
